### ISSUE TITLE
Is Redmine 3.2.0 supported?

### ISSUE THREAD

**Issue by octoquad** [luismaia/redmine_email_fetcher#18]
Hi,

I'm currently running this plugin on Redmine 3.1.3. We would like to move to 3.2.0 at some point, but there is no information in the README on supported versions of Redmine for this plugin. Is it possible to add supported versions in the README to quickly identify if it is safe to upgrade?

Thanks for this great plugin!

**Comment by nixmomo** [comment]
Yes works fine with 3.2.

**Comment by octoquad** [comment]
Thanks, just upgraded to 3.2.2 but now get: 

> $ sudo -u redmine -H rake -T redmine:plugins:email_fetcher RAILS_ENV=production
> rake aborted!
> Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 11.1.2. Prepending `bundle exec` to your command may solve this.
> /home/redmine/redmine/config/boot.rb:4:in `<top (required)>'
> /home/redmine/redmine/config/application.rb:1:in`<top (required)>'
> /home/redmine/redmine/Rakefile:5:in `<top (required)>'
> LoadError: cannot load such file -- bundler/setup
> /home/redmine/redmine/config/boot.rb:4:in`<top (required)>'
> /home/redmine/redmine/config/application.rb:1:in `<top (required)>'
> /home/redmine/redmine/Rakefile:5:in`<top (required)>'
> (See full trace by running task with --trace)

**Comment by octoquad** [comment]
Ok so, this works:

`$ sudo -u redmine -H bundle exec rake -T redmine:plugins:email_fetcher RAILS_ENV=production`
`$ sudo -u redmine -H bundle exec /usr/local/bin/rake -f /path/to/redmine/Rakefile redmine:plugins:email_fetcher:fetch_all_emails RAILS_ENV=production`

**Comment by nixmomo** [comment]
Sry haven't seen it... You can upgrade your rake too.... Your Error shows that your Rake ist installed in Version 10.4.2 and the Plugin require 11.1.2

**Comment by octoquad** [comment]
@nixmomo No problem, this plugin is working fine with Redmine 3.3.0 as well.
