### ISSUE TITLE
500 error when by adding new configuration

### ISSUE THREAD

**Issue by denisgolius** [luismaia/redmine_email_fetcher#35]
Current user: admin (id=1)
  Rendered plugins/redmine_email_fetcher/app/views/email_configurations/_form.html.erb (4.5ms)
  Rendered plugins/redmine_email_fetcher/app/views/email_configurations/new.html.erb within layouts/base (17.6ms)
Completed 500 Internal Server Error in 56ms (ActiveRecord: 18.2ms)

ActionView::Template::Error (undefined method `humanize' for nil:NilClass):
    12:         <p><%= f.select :flg_active, [['True', 'true'], ['False', 'false']],
    13:                         { label: l(:field_flg_active), required: true } %> </p>
    14:
    15:         <p>
    16:           <%= f.label '', { label: l(:field_last_fetch_at) } %>
    17:           <%- if @email_configuration.last_fetch_at.nil? %>
    18:               <%= '---' %>
  config/initializers/10-patches.rb:18:in `human_attribute_name'
  plugins/redmine_email_fetcher/app/views/email_configurations/_form.html.erb:15:in `block in _plugins_redmine_email_fetcher_app_views_email_configuratio
ns__form_html_erb__1117396829624187838_24086020'
  app/helpers/application_helper.rb:1190:in `labelled_form_for'
  plugins/redmine_email_fetcher/app/views/email_configurations/_form.html.erb:1:in `_plugins_redmine_email_fetcher_app_views_email_configurations__form_h
tml_erb__1117396829624187838_24086020'
  plugins/redmine_email_fetcher/app/views/email_configurations/new.html.erb:3:in `_plugins_redmine_email_fetcher_app_views_email_configurations_new_html_
erb__3255224410208670228_24055640'
  plugins/redmine_email_fetcher/app/controllers/email_configurations_controller.rb:32:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode
![photo_2017-12-08_09-52-29](https://user-images.githubusercontent.com/5650611/33756929-7b35bce0-dc00-11e7-9297-f8f862c70625.jpg)

`Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  redmine_custom_reports         0.1.5
  redmine_email_fetcher          0.3.1
  redmine_issue_checklist        2.1.0
  redmine_issue_template         1.0.7
  redmine_lightbox2              0.4.3`

percona mysql server + nginx 1.12.2&mod_passenger + Ubuntu server 16.04

**Comment by Niremizov** [comment]
Same here.

**Comment by Niremizov** [comment]
Fork https://github.com/salmanmp/redmine_email_fetcher/branches branch patch-1 works. You can use it till pull request is not merged https://github.com/luismaia/redmine_email_fetcher/pull/33

**Comment by denisgolius** [comment]
Thank you! It's works! :+1:

**Comment by denisgolius** [comment]
![default](https://user-images.githubusercontent.com/5650611/33823249-227b406a-de63-11e7-9c7e-3e49e19d556c.png)

Login or password incorrect : ( Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure))

How to authorize this app ? =)
