### ISSUE TITLE
More than one E-Mail Accounts

### ISSUE THREAD

**Issue by astoeffer** [luismaia/redmine_email_fetcher#6]
Hi,
I have confgured two E-Mail Account to fetch emails from. The first accounts work as expected.
The second only, if I manually fetch emails, with the cron job not.

If I start fetching e-mails fromt the command line I get this error messages:
"** Invoke redmine:plugins:email_fetcher:fetch_all_emails (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:email_fetcher:fetch_all_emails
rake aborted!
undefined method `trace' for #<Class:0x000000033928a0>
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
/var/www/support.learnforge.de/web/plugins/redmine_email_fetcher/app/models/email_configuration.rb:48:in `block in fetch_all_emails'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/delegation.rb:6:in `each'
/var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/relation/delegation.rb:6:in `each'
/var/www/support.learnforge.de/web/plugins/redmine_email_fetcher/app/models/email_configuration.rb:43:in `fetch_all_emails'
/var/www/support.learnforge.de/web/plugins/redmine_email_fetcher/lib/tasks/email_fetcher.rake:15:in `block (4 levels) in <top (required)>'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:email_fetcher:fetch_all_emails
"

I'm not a Ruby on Rails developer, so I need suggestions whats wrong.
I'use Redmine 2.5.3 in Debian Wheezy

Thanks 
Andreas

**Comment by luismaia** [comment]
@astoeffer - Could you please test and let me know if the current trunk solves your issue.
Thanks a lot!

**Comment by astoeffer** [comment]
Hi Luis,

now it worked Thank you for fixing this :-)

Andreas
