### ISSUE TITLE
Error fetching mails: "Unable to determine target project"

### ISSUE THREAD

**Issue by saz** [luismaia/redmine_email_fetcher#8]
I'm trying to get your plugin working, but I see the following error message in my logs:
`MailHandler: missing information from User Name: Unable to determine target project`

"User Name" is the name of the sender. The project is configured in email configurations.
It looks like, as if the project isn't passed to the MailHandler task, which then fails, as there is
no project set in the mail body.

**Comment by luismaia** [comment]
Hi @saz ,

Could you please let me know what is your: 
- Redmine version
- Rails version
- Ruby version
- redmine_email_fetcher version

Additionally, could you also provide me your email configuration (except the password)
(e.g. EmailConfiguration.all)

Finally, what is the message you get when you test the configuration (in the plugin administration page)?

**Comment by saz** [comment]
- Redmine version 2.5.1.stable
- Rails version 3.2.21
- Ruby version 2.0.0-p384
- redmine_email_fetcher version 0.3.0

What's the easiest way to get the email configuration in a format which will help you?

Testing the configuration: `Configuration tested successfully`
Fetching on the settings page: `Configuration fetched successfully`

The error message from MailHandler is still the same.

**Comment by luismaia** [comment]
Thanks a lot for the information.
I will try to test it later today...

To get the email configuration information, just go to your Redmine application folder using the terminal and execute:
`rails console`

And then inside the rails console (to get the output I need) execute:
`EmailConfiguration.all`

P.S. - If you have a chance, please upgrade redmine_email_fetcher to version 0.3.1

**Comment by luismaia** [comment]
Using your configuration I was able to obtain the following error:
`MailHandler: ignoring email from unknown user`

This error is solved in version 0.3.1 (https://github.com/luismaia/redmine_email_fetcher/pull/7).

Could you please upgrade redmine_email_fetcher to version 0.3.1 and let me know if it also solves yours.

**Comment by saz** [comment]
It looks like, as it is working with 0.3.1 now. Thanks! I'll close this issue. If the problem still exists, I'll reopen this one.
